
cc_library(
    name = "container",
    srcs = glob([
        "*.cpp"
    ]),
    hdrs = glob([
        "*.h"
    ]),
    deps = [
        "//util"    
    ],
    visibility = ["//visibility:public"]
)