cc_test(
    name = "test_type_list",
    srcs = [
        "test_type_list.cpp",
    ],
    deps = [
        "//container",
        "@gtest//:gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "test_tuple",
    srcs = [
        "test_tuple.cpp",
    ],
    deps = [
        "//container",
        "@gtest//:gtest",
        "@gtest//:gtest_main",
    ],
)